name: Crystal CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
    - name: Download a Build Artifact

  uses: actions/download-artifact@v2.1.1

  with:

    # Artifact name

    name: # optional

    # Destination path

    path: # optional
